/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 chair.gltf --transform 
Files: chair.gltf [71.58MB] > chair-transformed.glb [2.89MB] (96%)
Author: Dirtrock (https://sketchfab.com/dirtrock)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gothic-chair-5bcc5557ba2e4999afc3d7ecd5e30de7
Title: Gothic Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cushion_cushion_0.geometry} material={materials.cushion} position={[0, -0.002, 0.027]} scale={0.009} />
      <mesh geometry={nodes.chair_wood_0.geometry} material={materials.wood} position={[0, 0.278, 0]} scale={0.009} />
      <mesh geometry={nodes.chair_chair_0.geometry} material={materials.chair} position={[0, 0.278, 0]} scale={0.009} />
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')
